# DATABASE Configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useSSL=false
    username: root
    password: toortoor
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  application:
    name: Library Management

# REST Confgiuration
  data:
    rest:
      base-path: /apis

  # SECURITY Configuration
  security:
    user:
      name: user
      password: password


